pipeline {
    agent any
    stages {
        stage('Test') {
            agent { docker maven '3.6' }
            steps {
                echo 'Running UnitTest'
                sh 'mvn clean test'
            }
        }
    }
}
