pipeline {
    agent any
    tools {
        maven 'm3'
        jdk 'jdk8'
    }
    stages {
        stage ('Initialize') {
            steps {
                sh '''
                    echo "PATH=${PATH}"
                    echo "M2_HOME=${M2_HOME}"
                   '''
            }
        }
        stage('Test') {
            steps {
                echo 'Running UnitTest'
                sh 'mvn clean test'
            }
        }
    }
}