pipeline {
    agent none
    stages {
        stage('Test') {
            agent { docker maven '3.6.0' }
            steps {
                echo 'Running UnitTest'
                mvn 'mvn clean test'
            }
        }
    }
}
